name: Latest blog post workflow

on:
  schedule: # Run workflow automatically
    - cron: '0 0 2-30/2 * *' # Will only run at 00:00 on even days
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in webhat.in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.webhat.in/feed/"
          max_post_count: 3
          retry_count: 1
          retry_wait_time: 10
